# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: users.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\rexample.users\"#\n\x04Test\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x90\x01\n\x0bUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06height\x18\x02 \x01(\x02\x12\x13\n\x0bhasFacebook\x18\x03 \x01(\x08\x12+\n\teyeColour\x18\x04 \x01(\x0e\x32\x18.example.users.EyeColour\x12!\n\x04test\x18\x05 \x03(\x0b\x32\x13.example.users.Test\"9\n\x0cUserResponse\x12\x13\n\x0buserMessage\x18\x01 \x01(\t\x12\x14\n\x0cscoreAverage\x18\x02 \x01(\x05*8\n\tEyeColour\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05GREEN\x10\x01\x12\x08\n\x04\x42LUE\x10\x02\x12\t\n\x05\x42ROWN\x10\x03\x32T\n\x0bUserService\x12\x45\n\x08scoreAvg\x12\x1a.example.users.UserRequest\x1a\x1b.example.users.UserResponse\"\x00\x42\nZ\x08users.pbb\x06proto3')

_EYECOLOUR = DESCRIPTOR.enum_types_by_name['EyeColour']
EyeColour = enum_type_wrapper.EnumTypeWrapper(_EYECOLOUR)
UNKNOWN = 0
GREEN = 1
BLUE = 2
BROWN = 3


_TEST = DESCRIPTOR.message_types_by_name['Test']
_USERREQUEST = DESCRIPTOR.message_types_by_name['UserRequest']
_USERRESPONSE = DESCRIPTOR.message_types_by_name['UserResponse']
Test = _reflection.GeneratedProtocolMessageType('Test', (_message.Message,), {
  'DESCRIPTOR' : _TEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:example.users.Test)
  })
_sym_db.RegisterMessage(Test)

UserRequest = _reflection.GeneratedProtocolMessageType('UserRequest', (_message.Message,), {
  'DESCRIPTOR' : _USERREQUEST,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:example.users.UserRequest)
  })
_sym_db.RegisterMessage(UserRequest)

UserResponse = _reflection.GeneratedProtocolMessageType('UserResponse', (_message.Message,), {
  'DESCRIPTOR' : _USERRESPONSE,
  '__module__' : 'users_pb2'
  # @@protoc_insertion_point(class_scope:example.users.UserResponse)
  })
_sym_db.RegisterMessage(UserResponse)

_USERSERVICE = DESCRIPTOR.services_by_name['UserService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010users.pb'
  _EYECOLOUR._serialized_start=273
  _EYECOLOUR._serialized_end=329
  _TEST._serialized_start=30
  _TEST._serialized_end=65
  _USERREQUEST._serialized_start=68
  _USERREQUEST._serialized_end=212
  _USERRESPONSE._serialized_start=214
  _USERRESPONSE._serialized_end=271
  _USERSERVICE._serialized_start=331
  _USERSERVICE._serialized_end=415
# @@protoc_insertion_point(module_scope)
