name: Backend

on:
  push:
    branches: [ master ]
    paths: src/server/**
  pull_request:
    branches: [ master ]
    paths: src/server/**

jobs:
  Run-Unit-Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build go
      working-directory: src/server
      run: go build -v ./...
    - name: Run server Tests
      working-directory: src/server
      run: go test -v ./...