name: Backend

on:
  push:
    branches: [ master ]
    paths: src/backend-service/**
  pull_request:
    branches: [ master ]
    paths: src/backend-service/**

jobs:
  Run-Unit-Testing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build go
      working-directory: src/backend-service
      run: go build -v ./...
    - name: Run backend Tests
      working-directory: src/backend-service
      run: go test -v ./...