name: Cli

on:
  push:
    branches: [ master ]
    paths: src/cli-service/**
  pull_request:
    branches: [ master ]
    paths: src/cli-service/**

jobs:
  Run-Unit-Testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install python dependencies
      run: |
        cd src/cli-service
        pip install pipenv==2021.5.29
        pipenv install --dev
        pipenv run pytest -v .