name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-minikube:
    runs-on: ubuntu-latest
    name: Deploy minikube kubernetes
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster
      run: kubectl get pods -A